version: '2'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest #mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyP@ssw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  webapp:
    image: garage_api
    depends_on: 
      - mssql
    container_name: webapp
    ports: 
      - "5000:80"