/*
 * GarageSeller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace GarageSeller.Api.Models
{         /// <summary>
        /// Gets or Sets Motor
        /// </summary>
        public enum Motor
        { 
            /// <summary>
            /// Enum DieselEnum for diesel
            /// </summary>
            [EnumMember(Value = "diesel")]
            DieselEnum = 1,
            
            /// <summary>
            /// Enum PetrolEnum for petrol
            /// </summary>
            [EnumMember(Value = "petrol")]
            PetrolEnum = 2,
            
            /// <summary>
            /// Enum HybridEnum for hybrid
            /// </summary>
            [EnumMember(Value = "hybrid")]
            HybridEnum = 3,
            
            /// <summary>
            /// Enum ElectricEnum for electric
            /// </summary>
            [EnumMember(Value = "electric")]
            ElectricEnum = 4
        }
}
