/*
 * GarageSeller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace GarageSeller.Api.Models
{         /// <summary>
        /// Gets or Sets Transmission
        /// </summary>
        public enum Transmission
        { 
            /// <summary>
            /// Enum ManualEnum for manual
            /// </summary>
            [EnumMember(Value = "manual")]
            ManualEnum = 1,
            
            /// <summary>
            /// Enum AutomaticEnum for automatic
            /// </summary>
            [EnumMember(Value = "automatic")]
            AutomaticEnum = 2
        }
}
